steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azuressie'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az webapp config appsettings set \
        --name gregg \
        --resource-group gregg_group \
        --settings @config/settings.json
    displayName: 'Apply App Settings from JSON'
